name: KwaiAutomatico APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install "cython==0.29.37"

          sudo apt-get update

          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            libtinfo6

      - name: Configurar Android SDK
        run: |
          mkdir -p "$HOME/.buildozer/android/platform/android-sdk"
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses || true
          "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"

      - name: Construir APK
        run: |
          buildozer android debug

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: KwaiAutomatico-APK
          path: bin/*.apk
